list_deadlines:
  path: /
  methods: [GET]
  defaults:
    _controller: RavuAlHemioTotstrichBundle:Deadline:list
    intPage: 0
    blnCompletedAlso: false

list_deadlines_page:
  path: /page/{intPage}
  methods: [GET]
  requirements:
    intPage: '\d+'
  defaults:
    _controller: RavuAlHemioTotstrichBundle:Deadline:list
    blnCompletedAlso: false

list_all_deadlines:
  path: /all
  methods: [GET]
  defaults:
    _controller: RavuAlHemioTotstrichBundle:Deadline:list
    intPage: 0
    blnCompletedAlso: true

list_all_deadlines_page:
  path: /all/page/{intPage}
  methods: [GET]
  requirements:
    intPage: '\d+'
  defaults:
    _controller: RavuAlHemioTotstrichBundle:Deadline:list
    blnCompletedAlso: true

add_deadline:
  path: /add
  methods: [POST]
  defaults:
    _controller: RavuAlHemioTotstrichBundle:Deadline:add

show_deadline_editor:
  path: /edit/{numID}
  methods: [GET]
  requirements:
    numID: '\d+'
  defaults:
    _controller: RavuAlHemioTotstrichBundle:Deadline:showEditor

edit_deadline:
  path: /edit/{numID}
  methods: [POST]
  requirements:
    numID: '\d+'
  defaults:
    _controller: RavuAlHemioTotstrichBundle:Deadline:edit

complete_deadline:
  path: /complete/{numID}
  methods: [POST]
  requirements:
    numID: '\d+'
  defaults:
    _controller: RavuAlHemioTotstrichBundle:Deadline:complete
